#!/usr/bin/env python3
"""
GenAI Report Email Sender
Sends GenAI insight reports via email with geek-style HTML formatting
"""

import argparse
import smtplib
import sys
import os
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from email.mime.image import MIMEImage
from email.utils import formataddr
from pathlib import Path
import re
import base64

try:
    import yaml
except ImportError:
    print("Error: pyyaml not installed. Install with: pip install pyyaml")
    sys.exit(1)

try:
    import markdown2
except ImportError:
    print("Error: markdown2 not installed. Install with: pip install markdown2")
    sys.exit(1)

try:
    import boto3
    from botocore.exceptions import ClientError, NoCredentialsError
except ImportError:
    print("Warning: boto3 not installed. S3 upload will not be available.")
    print("Install with: pip install boto3")
    boto3 = None


class ReportMailer:
    """Email sender for GenAI insight reports"""

    def __init__(self, config_path):
        """
        Initialize mailer with configuration

        Args:
            config_path: Path to email config YAML file
        """
        self.config = self._load_config(config_path)
        self.config_dir = Path(config_path).parent

    def _load_config(self, config_path):
        """Load email configuration from YAML file"""
        try:
            with open(config_path, 'r') as f:
                config = yaml.safe_load(f)

            # Validate required fields
            required = ['smtp', 'sender', 'recipients']
            for field in required:
                if field not in config:
                    raise ValueError(f"Missing required field: {field}")

            # Resolve environment variables in password
            config = self._resolve_env_vars(config)

            return config
        except Exception as e:
            print(f"Error loading config: {e}")
            sys.exit(1)

    def _resolve_env_vars(self, config):
        """
        Resolve environment variables in config

        Supports:
        - ${ENV_VAR} format
        - Empty or missing password (reads from SMTP_PASSWORD)
        """
        # Handle SMTP password
        password = config.get('smtp', {}).get('password', '')

        if not password or password.strip() == '':
            # Empty password, try SMTP_PASSWORD env var
            password = os.environ.get('SMTP_PASSWORD', '')
            if not password:
                raise ValueError("SMTP password not set. Set SMTP_PASSWORD environment variable or add password to config.")
        elif password.startswith('${') and password.endswith('}'):
            # ${ENV_VAR} format
            env_var = password[2:-1]
            password = os.environ.get(env_var, '')
            if not password:
                raise ValueError(f"Environment variable {env_var} not set")

        config['smtp']['password'] = password

        return config

    def convert_markdown_to_html(self, markdown_path):
        """
        Convert Markdown report to HTML with geek-style CSS

        Args:
            markdown_path: Path to Markdown report file

        Returns:
            HTML string with embedded CSS
        """
        # Read Markdown content
        with open(markdown_path, 'r', encoding='utf-8') as f:
            markdown_content = f.read()

        # Convert Markdown to HTML
        html_body = markdown2.markdown(
            markdown_content,
            extras=['tables', 'fenced-code-blocks', 'header-ids']
        )

        # Get geek-style CSS
        css = self._get_geek_style_css()

        # Build complete HTML
        html = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>GenAI Insight Report</title>
    <style>{css}</style>
</head>
<body>
    <div class="container">
        {html_body}
        <footer>
            <p>Generated by GenAI Insight Reporter | Powered by Claude | <a href="https://d2085bnaxxamc7.cloudfront.net/index.html">更多报告</a></p>
        </footer>
    </div>
</body>
</html>"""

        # Replace image paths with inline CID references
        html = self._replace_image_paths_with_cid(html, markdown_path)

        return html

    def _replace_image_paths_with_cid(self, html, markdown_path):
        """
        Replace image paths with CID references for inline embedding

        Args:
            html: HTML content
            markdown_path: Path to original markdown file (for resolving image paths)

        Returns:
            HTML with CID references
        """
        markdown_dir = Path(markdown_path).parent

        # Find all image tags
        img_pattern = r'<img\s+[^>]*src="([^"]+)"[^>]*>'

        def replace_img(match):
            img_path = match.group(1)

            # Resolve relative paths
            if not img_path.startswith(('http://', 'https://', 'cid:')):
                full_path = (markdown_dir / img_path).resolve()

                # Generate CID from filename
                cid = Path(img_path).name.replace('.', '_')

                # Replace src with cid
                return match.group(0).replace(f'src="{img_path}"', f'src="cid:{cid}"')

            return match.group(0)

        return re.sub(img_pattern, replace_img, html)

    def _get_geek_style_css(self):
        """Get Claude Code style CSS using Anthropic brand colors - Light Theme"""
        return """
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }

        body {
            background: linear-gradient(180deg, #f7f5f0 0%, #faf9f5 50%, #f7f5f0 100%);
            color: #2a2825;
            font-family: Georgia, 'Times New Roman', serif;
            font-size: 16px;
            line-height: 1.75;
            padding: 60px 20px;
            min-height: 100vh;
        }

        .container {
            max-width: 900px;
            margin: 0 auto;
            background: #ffffff;
            border: 1px solid #e8e6dc;
            border-radius: 12px;
            padding: 56px;
            box-shadow:
                0 1px 3px rgba(0, 0, 0, 0.05),
                0 8px 24px rgba(0, 0, 0, 0.08);
            position: relative;
        }

        .container::before {
            content: '';
            position: absolute;
            top: 0;
            left: 0;
            right: 0;
            height: 2px;
            background: linear-gradient(90deg,
                transparent 0%,
                rgba(217, 119, 87, 0.2) 50%,
                transparent 100%);
        }

        h1 {
            color: #d97757;
            font-size: 42px;
            font-weight: 600;
            margin-bottom: 28px;
            padding-bottom: 20px;
            border-bottom: 2px solid rgba(217, 119, 87, 0.25);
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Arial, sans-serif;
            letter-spacing: -0.8px;
            line-height: 1.15;
        }

        h2 {
            color: #d97757;
            font-size: 30px;
            font-weight: 600;
            margin-top: 48px;
            margin-bottom: 20px;
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Arial, sans-serif;
            letter-spacing: -0.5px;
            line-height: 1.25;
            position: relative;
            padding-left: 16px;
        }

        h2::before {
            content: '';
            position: absolute;
            left: 0;
            top: 50%;
            transform: translateY(-50%);
            width: 4px;
            height: 24px;
            background: linear-gradient(180deg, #d97757 0%, rgba(217, 119, 87, 0.3) 100%);
            border-radius: 2px;
        }

        h3 {
            color: #5286b8;
            font-size: 22px;
            font-weight: 600;
            margin-top: 36px;
            margin-bottom: 14px;
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Arial, sans-serif;
            line-height: 1.35;
            letter-spacing: -0.3px;
        }

        h4 {
            color: #657a4a;
            font-size: 18px;
            font-weight: 600;
            margin-top: 28px;
            margin-bottom: 12px;
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Arial, sans-serif;
            line-height: 1.4;
            letter-spacing: -0.2px;
        }

        p {
            margin-bottom: 18px;
            color: #3a3731;
            line-height: 1.8;
        }

        blockquote {
            border-left: 3px solid #d97757;
            margin: 28px 0;
            color: #6b6962;
            background: linear-gradient(135deg, rgba(247, 245, 240, 0.8) 0%, rgba(250, 249, 245, 0.5) 100%);
            padding: 20px 20px 20px 24px;
            border-radius: 6px;
        }

        blockquote p {
            margin-bottom: 8px;
            color: #6b6962;
        }

        blockquote p:last-child {
            margin-bottom: 0;
        }

        a {
            color: #5286b8;
            text-decoration: none;
            transition: all 0.2s ease;
            border-bottom: 1px solid transparent;
        }

        a:hover {
            color: #3a6a96;
            border-bottom-color: rgba(82, 134, 184, 0.3);
        }

        strong {
            color: #141413;
            font-weight: 700;
        }

        code {
            background: rgba(232, 230, 220, 0.6);
            color: #c55a3a;
            padding: 4px 10px;
            border-radius: 5px;
            font-family: 'SF Mono', 'Monaco', 'Menlo', 'Consolas', monospace;
            font-size: 14px;
            border: 1px solid rgba(217, 119, 87, 0.2);
            letter-spacing: -0.3px;
        }

        pre {
            background: #f7f5f0;
            border: 1px solid #e8e6dc;
            border-radius: 8px;
            padding: 24px;
            overflow-x: auto;
            margin: 24px 0;
        }

        pre code {
            background-color: transparent;
            padding: 0;
            border: none;
            color: #3a3731;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            margin: 28px 0;
            background: #fefefe;
            border: 1px solid #e8e6dc;
            border-radius: 8px;
            overflow: hidden;
            box-shadow: 0 2px 8px rgba(0, 0, 0, 0.04);
        }

        th {
            background: linear-gradient(180deg, #f7f5f0 0%, #f2f0eb 100%);
            color: #d97757;
            padding: 16px 18px;
            text-align: left;
            font-weight: 600;
            border-bottom: 2px solid rgba(217, 119, 87, 0.25);
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Arial, sans-serif;
            font-size: 14px;
            letter-spacing: 0.3px;
            text-transform: uppercase;
        }

        td {
            padding: 14px 18px;
            border-bottom: 1px solid #f0eeeb;
            color: #3a3731;
        }

        tr:last-child td {
            border-bottom: none;
        }

        tr:hover {
            background-color: rgba(247, 245, 240, 0.5);
        }

        img {
            max-width: 100%;
            height: auto;
            display: block;
            margin: 40px auto;
            border-radius: 10px;
            border: 1px solid #e8e6dc;
            box-shadow:
                0 4px 12px rgba(0, 0, 0, 0.08),
                0 1px 3px rgba(0, 0, 0, 0.04);
        }

        hr {
            border: none;
            height: 1px;
            background: linear-gradient(90deg,
                transparent 0%,
                rgba(176, 174, 165, 0.3) 20%,
                rgba(176, 174, 165, 0.3) 80%,
                transparent 100%);
            margin: 48px 0;
        }

        ul, ol {
            margin: 18px 0 18px 36px;
            color: #3a3731;
        }

        li {
            margin-bottom: 12px;
            line-height: 1.75;
        }

        li::marker {
            color: #d97757;
        }

        footer {
            margin-top: 64px;
            padding-top: 28px;
            border-top: 1px solid rgba(232, 230, 220, 0.8);
            text-align: center;
            color: #8a8781;
            font-size: 13px;
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Arial, sans-serif;
        }

        /* Metric highlights */
        .metric {
            background: linear-gradient(135deg, rgba(120, 140, 93, 0.08) 0%, rgba(120, 140, 93, 0.04) 100%);
            border-left: 4px solid #788c5d;
            padding: 18px 24px;
            margin: 20px 0;
            border-radius: 6px;
        }

        .metric strong {
            color: #141413;
        }
        """

    def attach_images(self, msg, markdown_path):
        """
        Attach images as inline attachments

        Args:
            msg: MIMEMultipart message object
            markdown_path: Path to markdown file
        """
        markdown_dir = Path(markdown_path).parent

        # Find image references in markdown
        with open(markdown_path, 'r', encoding='utf-8') as f:
            content = f.read()

        # Find all image paths
        img_pattern = r'!\[.*?\]\(([^)]+)\)'
        image_paths = re.findall(img_pattern, content)

        for img_path in image_paths:
            # Skip external URLs
            if img_path.startswith(('http://', 'https://')):
                continue

            # Resolve path
            full_path = (markdown_dir / img_path).resolve()

            if not full_path.exists():
                print(f"Warning: Image not found: {full_path}")
                continue

            # Read image
            try:
                with open(full_path, 'rb') as f:
                    img_data = f.read()

                # Create MIMEImage
                image = MIMEImage(img_data)

                # Set CID (Content-ID)
                cid = full_path.name.replace('.', '_')
                image.add_header('Content-ID', f'<{cid}>')
                image.add_header('Content-Disposition', 'inline', filename=full_path.name)

                # Attach to message
                msg.attach(image)
                print(f"Attached image: {full_path.name} (CID: {cid})")

            except Exception as e:
                print(f"Warning: Failed to attach image {full_path}: {e}")

    def _list_s3_reports(self, s3_client, bucket_name, prefix):
        """
        List all HTML reports in S3 bucket

        Args:
            s3_client: boto3 S3 client
            bucket_name: S3 bucket name
            prefix: S3 key prefix

        Returns:
            List of report dictionaries with 'key', 'date', 'size', 'last_modified'
        """
        try:
            # List objects in bucket
            paginator = s3_client.get_paginator('list_objects_v2')

            if prefix:
                prefix = prefix.rstrip('/') + '/'
                pages = paginator.paginate(Bucket=bucket_name, Prefix=prefix)
            else:
                pages = paginator.paginate(Bucket=bucket_name)

            reports = []
            for page in pages:
                if 'Contents' not in page:
                    continue

                for obj in page['Contents']:
                    key = obj['Key']

                    # Skip index.html and non-HTML files
                    if key.endswith('index.html') or not key.endswith('.html'):
                        continue

                    # Extract date from filename
                    filename = Path(key).name
                    date_match = re.search(r'(\d{4})-(\d{2})-(\d{2})', filename)

                    if date_match:
                        reports.append({
                            'key': key,
                            'filename': filename,
                            'date': f"{date_match.group(1)}-{date_match.group(2)}-{date_match.group(3)}",
                            'size': obj['Size'],
                            'last_modified': obj['LastModified']
                        })

            # Sort by date (newest first)
            reports.sort(key=lambda x: x['date'], reverse=True)

            return reports

        except Exception as e:
            print(f"Warning: Failed to list S3 reports: {e}")
            return []

    def _generate_index_html(self, reports, custom_domain=None, region='us-east-1', bucket_name=None):
        """
        Generate index.html page listing all reports

        Args:
            reports: List of report dictionaries
            custom_domain: Custom domain for links
            region: AWS region
            bucket_name: S3 bucket name

        Returns:
            HTML string for index page
        """
        # Generate report list HTML
        report_rows = []
        for report in reports:
            # Generate URL
            key = report['key'].split("/")[-1]
            url = f"https://d2085bnaxxamc7.cloudfront.net/{key}"

            # Format size
            size_kb = report['size'] / 1024
            if size_kb < 1024:
                size_str = f"{size_kb:.1f} KB"
            else:
                size_str = f"{size_kb/1024:.1f} MB"

            # Format date
            date_obj = report['last_modified']
            modified_str = date_obj.strftime('%Y-%m-%d %H:%M UTC')

            report_rows.append(f"""
                <tr>
                    <td><a href="{url}" class="report-link">{report['date']}</a></td>
                    <td>{size_str}</td>
                    <td>{modified_str}</td>
                </tr>
            """)

        reports_html = "\n".join(report_rows) if report_rows else """
                <tr>
                    <td colspan="3" style="text-align: center; color: #8a8781;">No reports available yet.</td>
                </tr>
        """

        # Get the same CSS style as reports
        css = self._get_geek_style_css()

        # Generate complete HTML
        html = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>GenAI Insight Reports - Index</title>
    <style>{css}

        .report-link {{
            font-family: 'SF Mono', 'Monaco', 'Menlo', 'Consolas', monospace;
            font-weight: 600;
            font-size: 15px;
            letter-spacing: -0.2px;
        }}

        .stats {{
            display: flex;
            gap: 32px;
            margin: 32px 0 48px 0;
            padding: 24px;
            background: linear-gradient(135deg, rgba(120, 140, 93, 0.08) 0%, rgba(120, 140, 93, 0.04) 100%);
            border-radius: 8px;
            border-left: 4px solid #788c5d;
        }}

        .stat-item {{
            flex: 1;
        }}

        .stat-label {{
            font-size: 12px;
            color: #8a8781;
            text-transform: uppercase;
            letter-spacing: 0.5px;
            margin-bottom: 6px;
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Arial, sans-serif;
        }}

        .stat-value {{
            font-size: 28px;
            color: #d97757;
            font-weight: 700;
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Arial, sans-serif;
        }}

        .header-subtitle {{
            color: #6b6962;
            font-size: 16px;
            margin-top: 12px;
            margin-bottom: 32px;
        }}
    </style>
</head>
<body>
    <div class="container">
        <h1>GenAI Insight Reports</h1>
        <p class="header-subtitle">
            Comprehensive analysis and insights on trending GenAI projects from GitHub
        </p>

        <div class="stats">
            <div class="stat-item">
                <div class="stat-label">Total Reports</div>
                <div class="stat-value">{len(reports)}</div>
            </div>
            <div class="stat-item">
                <div class="stat-label">Latest Update</div>
                <div class="stat-value">{reports[0]['date'] if reports else 'N/A'}</div>
            </div>
        </div>

        <h2>Available Reports</h2>
        <p>Click on any date to view the full report with detailed analysis and visualizations.</p>

        <table>
            <thead>
                <tr>
                    <th>Report Date</th>
                    <th>Size</th>
                    <th>Last Modified</th>
                </tr>
            </thead>
            <tbody>
{reports_html}
            </tbody>
        </table>

        <footer>
            <p>Generated by GenAI Insight Reporter | Powered by Claude</p>
            <p style="margin-top: 8px; font-size: 12px;">Last updated: {reports[0]['last_modified'].strftime('%Y-%m-%d %H:%M UTC') if reports else 'N/A'}</p>
        </footer>
    </div>
</body>
</html>"""

        return html

    def upload_to_s3(self, html_content, markdown_path):
        """
        Upload HTML content to S3 bucket and update index page

        Args:
            html_content: HTML content to upload
            markdown_path: Path to markdown file (for extracting date)

        Returns:
            S3 URL if successful, None otherwise
        """
        # Check if boto3 is available
        if boto3 is None:
            print("⚠️  boto3 not installed. Skipping S3 upload.")
            return None

        # Check if S3 config exists
        s3_config = self.config.get('s3')
        if not s3_config or not s3_config.get('enabled', False):
            print("S3 upload not enabled in config. Skipping.")
            return None

        try:
            # Extract date from filename
            filename = Path(markdown_path).stem
            date_match = re.search(r'(\d{4})(\d{2})(\d{2})', filename)
            if date_match:
                date_str = f"{date_match.group(1)}-{date_match.group(2)}-{date_match.group(3)}"
            else:
                # Fallback to current date
                from datetime import datetime
                date_str = datetime.now().strftime('%Y-%m-%d')

            # Build S3 key
            s3_key = f"{date_str}.html"
            prefix = s3_config.get('prefix', '').rstrip('/')
            if prefix:
                s3_key = f"{prefix}/{s3_key}"

            bucket_name = s3_config['bucket']
            region = s3_config.get('region', 'us-east-1')
            custom_domain = s3_config.get('custom_domain')

            print(f"Uploading to S3: s3://{bucket_name}/{s3_key}")

            # Create S3 client
            s3_client = boto3.client('s3', region_name=region)

            # Upload HTML content
            s3_client.put_object(
                Bucket=bucket_name,
                Key=s3_key,
                Body=html_content.encode('utf-8'),
                ContentType='text/html',
                ContentEncoding='utf-8'
            )

            # Generate S3 URL
            s3_url = f"https://{bucket_name}.s3.{region}.amazonaws.com/{s3_key}"
            if custom_domain:
                s3_url = f"https://{custom_domain}/{s3_key}"

            print(f"✅ HTML uploaded to S3: {s3_url}")

            # Update index page
            print("Updating index page...")
            self._update_index_page(s3_client, bucket_name, region, prefix, custom_domain)

            return s3_url

        except NoCredentialsError:
            print("❌ AWS credentials not found. Configure AWS CLI or set environment variables.")
            return None
        except ClientError as e:
            print(f"❌ S3 upload failed: {e}")
            return None
        except Exception as e:
            print(f"❌ Unexpected error during S3 upload: {e}")
            import traceback
            traceback.print_exc()
            return None

    def _update_index_page(self, s3_client, bucket_name, region, prefix, custom_domain):
        """
        Generate and upload index.html page

        Args:
            s3_client: boto3 S3 client
            bucket_name: S3 bucket name
            region: AWS region
            prefix: S3 key prefix
            custom_domain: Custom domain for links
        """
        try:
            # List all reports
            reports = self._list_s3_reports(s3_client, bucket_name, prefix)

            if not reports:
                print("No reports found to generate index.")
                return

            # Generate index HTML
            index_html = self._generate_index_html(
                reports,
                custom_domain=custom_domain,
                region=region,
                bucket_name=bucket_name
            )

            # Build index key
            index_key = 'index.html'
            if prefix:
                index_key = f"{prefix}/index.html"

            # Upload index page
            s3_client.put_object(
                Bucket=bucket_name,
                Key=index_key,
                Body=index_html.encode('utf-8'),
                ContentType='text/html',
                ContentEncoding='utf-8'
            )

            # Generate index URL
            if custom_domain:
                index_url = f"https://{custom_domain}/{index_key}"
            else:
                index_url = f"https://{bucket_name}.s3.{region}.amazonaws.com/{index_key}"

            print(f"✅ Index page updated: {index_url}")
            print(f"   Total reports listed: {len(reports)}")

        except Exception as e:
            print(f"⚠️  Failed to update index page: {e}")
            import traceback
            traceback.print_exc()

    def send_email(self, markdown_path, subject=None, dry_run=False):
        """
        Send email with report

        Args:
            markdown_path: Path to Markdown report file
            subject: Custom subject line (optional)
            dry_run: If True, only preview HTML without sending

        Returns:
            True if successful, False otherwise
        """
        try:
            # Generate HTML
            print("Converting Markdown to HTML...")
            html_content = self.convert_markdown_to_html(markdown_path)

            # Read plain text version
            with open(markdown_path, 'r', encoding='utf-8') as f:
                plain_content = f.read()

            if dry_run:
                # Save preview
                preview_path = 'preview.html'
                with open(preview_path, 'w', encoding='utf-8') as f:
                    f.write(html_content)
                print(f"✅ Preview saved to: {preview_path}")
                print("Open in browser to view")
                return True

            # Build subject
            if not subject:
                # Extract date from report filename
                filename = Path(markdown_path).stem
                date_match = re.search(r'(\d{4})(\d{2})(\d{2})', filename)
                if date_match:
                    date_str = f"{date_match.group(1)}-{date_match.group(2)}-{date_match.group(3)}"
                else:
                    date_str = "Latest"

                subject_prefix = self.config.get('email', {}).get('subject_prefix', '[GenAI Insight]')
                subject = f"{subject_prefix} Report - {date_str}"

            # Create message
            msg = MIMEMultipart('related')
            msg['Subject'] = subject
            msg['From'] = formataddr((
                self.config['sender']['name'],
                self.config['sender']['email']
            ))
            msg['To'] = ', '.join(self.config['recipients']['to'])

            if self.config['recipients'].get('cc'):
                msg['Cc'] = ', '.join(self.config['recipients']['cc'])

            if self.config.get('email', {}).get('reply_to'):
                msg['Reply-To'] = self.config['email']['reply_to']

            # Create alternative part for HTML and plain text
            msg_alternative = MIMEMultipart('alternative')
            msg.attach(msg_alternative)

            # Attach plain text version
            msg_alternative.attach(MIMEText(plain_content, 'plain', 'utf-8'))

            # Attach HTML version
            msg_alternative.attach(MIMEText(html_content, 'html', 'utf-8'))

            # Upload to S3 (if enabled)
            s3_url = self.upload_to_s3(html_content, markdown_path)

            # Attach images
            print("Attaching images...")
            self.attach_images(msg, markdown_path)

            # Send email
            print(f"Connecting to SMTP server: {self.config['smtp']['host']}:{self.config['smtp']['port']}")

            # Build recipient list
            all_recipients = list(self.config['recipients']['to'])
            if self.config['recipients'].get('cc'):
                all_recipients.extend(self.config['recipients']['cc'])
            if self.config['recipients'].get('bcc'):
                all_recipients.extend(self.config['recipients']['bcc'])

            # Connect and send
            smtp_config = self.config['smtp']

            # Determine connection type
            if smtp_config.get('use_ssl', False):
                # SSL connection (port 465 typically)
                server = smtplib.SMTP_SSL(smtp_config['host'], smtp_config['port'])
            elif smtp_config.get('use_tls', True):
                # TLS connection (port 587 typically)
                server = smtplib.SMTP(smtp_config['host'], smtp_config['port'])
                server.starttls()
            else:
                # Plain connection (not recommended)
                server = smtplib.SMTP(smtp_config['host'], smtp_config['port'])

            server.login(smtp_config['username'], smtp_config['password'])
            server.send_message(msg, to_addrs=all_recipients)
            server.quit()

            print(f"✅ Email sent successfully!")
            print(f"   Subject: {subject}")
            print(f"   To: {', '.join(self.config['recipients']['to'][:3])}" +
                  (f" and {len(self.config['recipients']['to'])-3} more"
                   if len(self.config['recipients']['to']) > 3 else ""))

            return True

        except Exception as e:
            print(f"❌ Error sending email: {e}")
            import traceback
            traceback.print_exc()
            return False


def main():
    """Main entry point"""
    parser = argparse.ArgumentParser(
        description='Send GenAI insight reports via email'
    )
    parser.add_argument(
        '--report',
        required=True,
        help='Path to Markdown report file'
    )
    parser.add_argument(
        '--config',
        required=True,
        help='Path to email config YAML file'
    )
    parser.add_argument(
        '--subject',
        help='Custom email subject line'
    )
    parser.add_argument(
        '--dry-run',
        action='store_true',
        help='Preview HTML without sending email'
    )

    args = parser.parse_args()

    # Validate paths
    if not Path(args.report).exists():
        print(f"Error: Report file not found: {args.report}")
        sys.exit(1)

    if not Path(args.config).exists():
        print(f"Error: Config file not found: {args.config}")
        sys.exit(1)

    # Send email
    mailer = ReportMailer(args.config)
    success = mailer.send_email(
        args.report,
        subject=args.subject,
        dry_run=args.dry_run
    )

    sys.exit(0 if success else 1)


if __name__ == "__main__":
    main()
